# Generated by Django 4.1.1 on 2022-09-14 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ably', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Verified',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=15, verbose_name='전화번호')),
                ('key', models.CharField(max_length=8, verbose_name='인증번호')),
                ('action', models.CharField(max_length=16, verbose_name='인증종류')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expired_at', models.DateTimeField()),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=15, verbose_name='전화번호'),
        ),
    ]
